apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: web
resources:
  - ../../base
patches:
  - target:
      kind: Ingress
    path: ingress-patch.yaml
namespace: default # kpt-set: ${DEPLOY_NAMESPACE}
commonAnnotations:
  version: 2.4.1-8b09e849--2023-04-22--944 # kpt-set: ${GIT_TAG}
images: # kpt-set: ${IMAGE_REF}
  - name: "qcon-guide"
    newName: "registry.ltc.bcit.ca/web-apps/qcon/qcon-guide"
    newTag: "2.4.1-75ee1728--2023-04-23--257" # {"$imagepolicy": "flux-system:qcon-guide-web:tag"}
